### ISSUE TITLE
Please support the "GitLab API Token" credential from GitLab Plugin

### ISSUE THREAD

**Issue by TBBle** [jenkinsci/gitlab-branch-source-plugin#107]
This plugin introduces "GitLab Personal Access Token", which appears to serve the same purpose as the ["GitLab API Token"](https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/connection/GitLabApiToken.java) from the GitLab Plugin.

It'd be nice if this plugin could consume GitLab API Tokens where it consumes GitLab Personal Access Token, to save duplication of credential entries.

And if it can't do that in the GitLab Server case, then it'd be nice if the "Convert login and password to token" feature also supported "Convert GitLab API Token to token", and even "Convert Secret Text to token", since it turns out our local Jenkins has API tokens for GitLab in the "Secret text" type too.

**Comment by TobiX** [comment]
The better way would be to extract credentials from both plugins into a new common plugin, since they don't share implementation in any other way (in fact, if you only use multibranch jobs, you don't need the "GitLab plugin" at all)

**Comment by spidey** [comment]
Even better to use a plain secret text credential. I'm using scripts that also reach the GitLab API and had to duplicate credential as secret text to be able to export it with `withCredentials`.

**Comment by majinghe** [comment]
I met the same issue with latest jenkins version
<img width="879" alt="Screen Shot 2021-08-28 at 4 21 48 PM" src="https://user-images.githubusercontent.com/42570491/131211524-573af4fd-359a-4d81-984b-6af095fce039.png">

From the [plugins docs](https://plugins.jenkins.io/gitlab-branch-source/), the token should be ` GitLab Personal Access Token`. 

In additon, the `GitLab API Token` generated in the same place with `GitLab Personal Access Token`. In my opinion, `GitLab Personal Access Token` should fit the both situation. Am i right?

**Comment by ljackiewicz** [comment]
Although using **GitLab API Token** from GitLab plugin doesn't seem like the best idea as many users won't use the rest of this plugin's features, I wonder if there is a reason why we have to use only **Personal Access Token** type credentials and why we cannot use any **StringCredentials** type credentials for this case, such as "secret text" provided by the Plain Credentials plugin or the "Vault Secret Text Credential" provided by the HashiCorp Vault plugin (which are supported by the GitLab plugin by the way).

Are there any obstacles to use StringCredentials type credentials too?
