### ISSUE TITLE
Hook executed successfully but returned HTTP 401 

### ISSUE THREAD

**Issue by bruceforlearn** [jenkinsci/gitlab-branch-source-plugin#115]
jenkins version : 2.276
GitLab Branch Source Plugin version: 1.5.3
OS:Centos7
GitLab Community Edition 13.0.10
I have Credentials verified for user,but Hook executed successfully but returned HTTP 401,gitlab webhook not works

please help 
![1](https://user-images.githubusercontent.com/29446582/106124104-b0d98980-6195-11eb-9457-d28b963b5a76.png)
![2](https://user-images.githubusercontent.com/29446582/106124107-b2a34d00-6195-11eb-8a0e-b88369ef42a8.png)
![3](https://user-images.githubusercontent.com/29446582/106124121-b46d1080-6195-11eb-82b3-90364d8ad0bc.png)

**Comment by bruceforlearn** [comment]
this is my <jenkins_url>/gitlab-webhook/post
![4](https://user-images.githubusercontent.com/29446582/106124379-fe55f680-6195-11eb-9fd9-ee2a5ca5cacf.png)

**Comment by coryasilva** [comment]
@bruceforlearn I was having the same problem with 1.5.4 and had to rollback to 1.5.1.  How did you solve this?

**Comment by ielshal** [comment]
I had similar issue .. fixed by updating `Secret Token` field to match token in credentials .. so it worth checking it.
