### ISSUE TITLE
Support triggering the build only if the commit affects defined directories

### ISSUE THREAD

**Issue by jmullo** [jenkinsci/gitlab-branch-source-plugin#126]
### Feature Request

I want to define a list of included/excluded directories (or regular expressions). The build will be triggered or not triggered based on comparing those lists to the content of the commit.

**Comment by ChristianCiach** [comment]
I think you can use this plugin to do that: https://github.com/jenkinsci/multibranch-build-strategy-extension-plugin

Have a look at the two screenshots.

**Comment by jmullo** [comment]
Thanks. Closing this.
