### ISSUE TITLE
GitLab Group: Support for Deploy Tokens

### ISSUE THREAD

**Issue by Opa-** [jenkinsci/gitlab-branch-source-plugin#134]
It'd be great for GitLab Group to support [Deploy Tokens](https://docs.gitlab.com/ee/user/project/deploy_tokens/) credentials as these kind of credentials can work for a whole group on GitLab. They can also work per-project like SSH Key.

**Comment by Opa-** [comment]
Oh ok, it was unclear to me how to use it.
I tried to register the token in Jenkins as `GitLab Personal Access Token` or `GitLab API Token` but these 2 types of credentials are not compatible with `Checkout Credentials`.
It makes sense because a deploy token has a dedicated username. This seems to work when registering the deploy token as a simple username/password credential in Jenkins.

Could you confirm this is the correct way to do it ?

Thanks :)

**Comment by ChristianCiach** [comment]
Sorry, I should have been more clear about that. 

Yes, you should register the deploy tokens as simple username/password credentials in jenkins. That's the way we are doing this. 

Anyway, I think this technically has nothing to do with the gitlab branch source plugin. The checkout is done (and the credentials are used) by the generic Git plugin of jenkins.

**Comment by Opa-** [comment]
Ok, thanks for the clarification 😃
