### ISSUE TITLE
Gitlab MR pipelines are not notified anymore (because of PR 128)

### ISSUE THREAD

**Issue by dcendents** [jenkinsci/gitlab-branch-source-plugin#135]
PR #128 breaks pipelines for merge requests.

### Version report

Jenkins and plugins versions report:

```
Jenkins 2.277.2
Gitlab branch source plugin 1.5.6
```

### Reproduction steps

On a project, I have jenkins configured to build only the Merge Requests and the main branch (`develop`) 

---

With version 1.5.5, when a Merge Request was building, in gitlab I could see in the project pipelines page that a pipeline had started for branch `branch-name` with the commit ref, where `branch-name` is the source branch of my merge request.

In the merge request page I could also see `Pipeline # 123 running for commit ref on branch-name`

---

Now with version 1.5.6, in gitlab in the project pipelines page it says that a pipeline has started for branch `MR-200` with the commit ref, where `MR-200` is the merge request 200 but not a valid git branch name.

In the merge request page it says `Checking pipeline status` indefinitely...

Since I have a condition that a pipeline must succeed to allow the merge request to be merged I'm stuck.

---

I don't propose to revert PR #128, but I think that when jenkins builds a merge request, the ref field should be set to the merge request source branch name.

Also it should be tested with tags as well

**Comment by dcendents** [comment]
The behavior for tags has also changed but it seems to work OK.

With 1.5.5 I could see a pipeline was started for branch-name on commit-ref
With 1.5.6 I can see a pipeline was started for tag-name on commit-ref

With both methods, in the project repository tags page the pipeline is picked correctly

**Comment by LinuxSuRen** [comment]
What version of Gitlab do you use? The public service or a private deploy?
