### ISSUE TITLE
GitLab Merge Request pipeline runs on merge request approval

### ISSUE THREAD

**Issue by Adityanr** [jenkinsci/gitlab-branch-source-plugin#148]
### Feature Request

An option to run a merge request job only when it is approved by someone. This is will prevent a merge request job being run every time a user pushes changes to the source branch.

**Related plugin**: gitlab source plugin

**Comment by julianxhokaxhiu** [comment]
I second this feature, would be extremely helpful to avoid building every kind of MR but only the ones the team really needs.

**Comment by spidey** [comment]
If we are adding these conditionals to building I'd add also add a configuration to skip draft MRs.

**Comment by Adityanr** [comment]
> If we are adding these conditionals to building I'd add also add a configuration to skip draft MRs.

that would be very useful.

**Comment by mifitous** [comment]
It would be very useful to have options in the configure window for:
Webhook Listener Conditions

- Always build pipeline on Open MR webhook
- Always build pipeline on Re-Open MR webhook
- Ignore build pipeline on MR Approval
- Ignore build pipeline on MR Un-Approval
- Ignore builds for non-code related MR updates
- ...

and any of the https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#merge-request-events

_The available values for object_attributes.action in the payload are:
- open
- close
- reopen
- update
- approved
- unapproved
- approval
- unapproval
- merge_

Did someonealready implemented WebhookListenerBuildConditionsTrait.stapler / WebhookListenerBuildConditionsTrait/config.jelly ?

It seems someone internally in our company got such code from the net, but I can't find it anywhere...

**Comment by mifitous** [comment]
Added 
![image](https://user-images.githubusercontent.com/16884890/212834006-6837eefe-bc27-4b69-a796-57f9cb3f634d.png)
to https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/266

**Comment by Adityanr** [comment]
thank you @mifitous

**Comment by mifitous** [comment]
@jetersen : we can close this one as fix was merged
