### ISSUE TITLE
Feature Trigger build on MR comment doesn't work 

### ISSUE THREAD

**Issue by usinelogicielle** [jenkinsci/gitlab-branch-source-plugin#153]
### Jenkins and plugins versions :

We are using **Jenkins 2.235.5** version,  **GitLab Branch Source 1.5.4** version and **GitLab 13.9** version

### Issue description : 
I tried to rebuild my pipeline via the "**Trigger build on merge request comment**" behaviour, but this option does not work. When I type the rebuild message in Gitlab, nothing happens in Jenkins. It seems that the rebuild is not triggered. 
![build_MR_commentaire](https://user-images.githubusercontent.com/73827301/128010956-577f8148-21bf-4b4d-be0e-87289d8c1c70.PNG)
![rebuild_commentaire_git](https://user-images.githubusercontent.com/73827301/128011516-e73663bb-47a5-4d42-97e6-c09aeb30f3b7.PNG)

I have this in my jenkins logs :
![Stacktrace_comment](https://user-images.githubusercontent.com/73827301/128018267-58b7b4c2-58d2-4e8d-b0e0-e4bd6e4c9a59.PNG)
Is there a work-around and is it a known issue? 
My server and my webhook are correctly configured and other behaviours I tried work properly. 
![web_hook_config](https://user-images.githubusercontent.com/73827301/128012862-6fa41704-0228-41b2-a4d1-fb8231e651ad.PNG)
![GitLab_server_config](https://user-images.githubusercontent.com/73827301/128018933-9e693831-1959-414c-bec9-8857bcd89c56.PNG)

Thanks for your help

**Comment by TobiX** [comment]
It seems note events aren't set up to create new jobs, so if you don't have a webhook for "Merge Requests Events", there may be no job which the "Note Event" could rebuild...

**Comment by usinelogicielle-cnes** [comment]
My Jenkins job already exists when I tried to rebuild my pipeline.

**Comment by usinelogicielle-cnes** [comment]
Hi @TobiX ,

To update the issue,  We can see that merge request events are in the webhook. And when we add a comment to rebuild, the job is present. Do you have an idea?

Kind regards

**Comment by Opa-** [comment]
You are using GitLab Branch Source 1.5.4 although this issue was fixed as part of [1.5.9](https://github.com/jenkinsci/gitlab-branch-source-plugin/releases/tag/gitlab-branch-source-1.5.9). See https://github.com/jenkinsci/gitlab-branch-source-plugin/issues/120 and https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/122 :wink:

**Comment by usinelogicielle** [comment]
Thanks for your response. We will test this version.
