### ISSUE TITLE
Latest release on Github is not really latest

### ISSUE THREAD

**Issue by Stikus** [jenkinsci/gitlab-branch-source-plugin#158]
![image](https://user-images.githubusercontent.com/41360525/131506244-9568506c-a87b-4b31-8a0d-370c0bbd376e.png)

Hello, thx for updates.
As you can see on screenshot - `latest` tag on release page is wrong. Can anyone fix it?

**Comment by LinuxSuRen** [comment]
Good catch!

![image](https://user-images.githubusercontent.com/1450685/131523159-696188e2-a5a0-488b-b83f-70838f15bfc9.png)
