### ISSUE TITLE
GitLab being notified of 2 builds per branch even when the discover strategy is configured as branch revision only

### ISSUE THREAD

**Issue by spidey** [jenkinsci/gitlab-branch-source-plugin#166]
Sometimes Merge Requests from Multibranch pipeline jobs using GitLab Branch Source plugin notify GitLab of 2 pipelines per build instead of only one. This messes with GitLab as it thinks that one pipeline is running forever.

### Version report
Unfortunately I can't easily run the versions fetching script on the Jenkins console, but I can list the most important versions manually:

| Plugin | Version |
|---|----|
|Jenkins | 2.263.4|
|GitLab Branch Source Plugin | 1.5.7|
|Job DSL | 1.77|
|Jenkins Git plugin | 4.7.1|
|Pipeline Utility Steps | 2.7.1 |
|Pipeline: Basic Steps | 2.23 |
|Pipeline: Build Step | 2.13 |
|Pipeline: Declarative | 1.8.4 |
|Pipeline: Groovy | 2.90 |
|Pipeline: Input Step | 2.12 |
|Pipeline: Job | 2.40 |
|Basic Branch Build Strategies Plugin | 1.3.2 |
|Branch API Plugin | 2.6.2|
|Gitlab API Plugin | 1.0.6|
|Pipeline: API | 2.42 |
|Pipeline: Declarative Extension Points API | 1.8.4 |
|Pipeline: Job | 2.40 |
|Pipeline: Model API | 1.8.4 |
|Pipeline: REST API Plugin | 2.19 |
|Pipeline: Stage Tags Metadata | 1.8.4 |
|Pipeline: Stage View Plugin | 2.19 |
|Pipeline: Step API | 2.23 |
|Pipeline: Supporting APIs | 3.8|

- What Operating System are you using (both controller, and any agents involved in the problem)?
Linux host running agents on K8s Linux.

### Reproduction steps
- Create a multibranch pipeline job connecting to GitLab
- Configure it to track only MRs and to build only the source branch from it
  In our case we have it configured with something like this:
  ```
                    traits {
                        gitLabBranchDiscovery {
                            strategyId(1) // Only branches not also listed as MRs
                        }
                        originMergeRequestDiscoveryTrait {
                            strategyId(2) // Discover Merge requests from origin, build the branch directly
                        }
                        headWildcardFilter {
                            includes("MR-*")
                            excludes('')
                        }
                    }
  ```
- Create a new MR from a branch
- Check triggered pipelines on GitLab for the MR
- Sometimes 2 pipelines are created

### Results
Expected result:
Only one pipeline job per branch/push is created on GitLab, as in the following example of a well behaving MR:
![Screen Shot 2021-11-02 at 19 51 01](https://user-images.githubusercontent.com/696327/139927693-5b2350f9-de83-484c-a474-e71efcacc457.png)

Actual result:
Two pipelines are triggered, one named jenkinsci/mr-merge and another one jenkinsci/mr-head, as the bad example from another MR, from the same project, generated automatically with the same configuration as the above one, just a few hours before:
![Screen Shot 2021-11-02 at 19 54 22](https://user-images.githubusercontent.com/696327/139927698-b4e48111-2c87-4552-8302-6f138938e747.png)

**Comment by spidey** [comment]
`sys-jenkins-premerge1` is the user configured on Jenkins handling the GitLab Branch Source plugin.
I'd like to first confirm if this is a known bug, as I couldn't find any tickets related to it here. And if it is not known I'd appreciate further instructions on how to debug this.

**Comment by temujin** [comment]
Faced same issue.

**Comment by spidey** [comment]
Further investigation points to the plugin correctly creating the `mr-head` GitLab CI job when beginning the pipeline, but incorrectly creating the `mr-merge` GitLab CI job when the Jenkins pipeline finishes and it's time to set the result.

So it's not 2 GitLab CI jobs being created at some point. It's a single one but with different names at the start and end of the Jenkins pipeline.

I'm almost positive this is a bug on the plugin code, I wonder why it's not consistent, though. Most of the times it works correctly updating the `mr-head` GitLab CI job at the start and end of the Jenkins pipeline.

**Comment by spidey** [comment]
I think I found the root cause: https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/efb7780f1000b1d116fb1c644ef2718cda34445a/src/main/java/io/jenkins/plugins/gitlabbranchsource/helpers/GitLabPipelineStatusNotifier.java#L128

On this line if there is "merge" on the job or run full name it will think it's "mr-merge". But we have branches and MRs titled with "merge" in them every now and then, and the issue arises. I'm thinking that in the beginning of the pipeline less information is available and thus it works correctly, but by the end more MR data is fetched and available and the `fullDisplayName` gets this info.

**Comment by spidey** [comment]
Ok, completely understood the issue and why it's flaky for me.
The plugin is trying to be smart and automatically detect the job kind from the build name, but we are appending the branch name to the build name, so builds are now `#1 - my_branch`, `#2 - my branch`, etc for the same MR. The thing is, sometimes we have a branch name that includes "merge" in it, and then the plugin incorrectly thinks it's a merge build. As the build name is updated on the pipeline itself, it dynamically changes after the first notification causing the second one to be incorrectly sent and creating the second GitLab CI job incorrectly.

The redacted branch names on the screenshots above hid this important evidence. On the case of the second screenshot, MR !2312, the branch name was `mr/master/caspers/rebase-diff-testing-do-not-merge`, for instance.

For us the fix will be updating the multibranch pipeline not to touch the build name (`currentBuild.displayName`). Hopefully it can be fixed on the plugin with a proper fix (perhaps adding separators to the "merge" being searched for as a quick fix, if it makes sense). In my case the multibranch setup already provides the links to the MR so having the branch name is not useful (it was before on our previous setup), but other use cases might still need to have "merge" somewhere. This bug only impacts MRs, though, as tags and branches don't have this possibility of multiple build configurations.

**Comment by Turiok** [comment]
@spidey If you can test the code?

**Comment by spidey** [comment]
I'll learn how to deploy Jenkins locally and test it, I was using my work's environment before and there the infra is maintained by a different team.

**Comment by spidey** [comment]
> @spidey If you can test the code?

Managed to reproduce the issue with publish plugin from Jenkins plugin marketplace and then the branch proposed without the issue. Tested all 3 configurations successfully: MR revision, merged result and both together.
