### ISSUE TITLE
Support for forks that are not mirrors, so that MRs are built

### ISSUE THREAD

**Issue by TBBle** [jenkinsci/gitlab-branch-source-plugin#167]
### Feature Request

We have a GitLab project which is a fork of another project from another team, in order to isolate artefacts and allow an MR flow.

This means we use MRs inside that fork from branches in the fork back to the fork's default branch.

I was puzzled by the lack of MR builds when I have the same Jenkins config and webhooks in both the upstream and fork, until I noticed

>  Starting branch indexing...
> 
> Ignoring merge requests as project is a mirror...

in the scan logs, which pointed me at [this unconditional code](https://github.com/jenkinsci/gitlab-branch-source-plugin/blob/gitlab-branch-source-1.5.9/src/main/java/io/jenkins/plugins/gitlabbranchsource/GitLabSCMSource.java#L324-L336), which always ignores MRs if a repo is a fork of another repo, even if it is not a [mirror](https://docs.gitlab.com/ee/user/project/repository/mirror/pull.html).

```java
                    if (gitlabProject.getForkedFromProject() == null) {
                        listener.getLogger()
                            .format(
                                "%nUnable to detect if it is a mirror or not still fetching MRs anyway...%n");
                        List<MergeRequest> mrs = gitLabApi.getMergeRequestApi()
                            .getMergeRequests(gitlabProject, Constants.MergeRequestState.OPENED);
                        mrs = mrs.stream().filter(mr -> mr.getSourceProjectId() != null)
                            .collect(Collectors.toList());
                        request.setMergeRequests(mrs);
                    } else {
                        listener.getLogger()
                            .format("%nIgnoring merge requests as project is a mirror...%n");
                    }
```

My initial thought was that this should be controlled by a strategy setting.

However, maybe it only makes sense to ignore MRs in a fork _if_ they are targeting the upstream repo (or perhaps any repo other than the current repo), since they will potentially be built by the CI for the upstream repo using the "Discover merge requests from forks" behaviour, i.e. something like

```java
                    if (gitlabProject.getForkedFromProject() == null) {
                        listener.getLogger()
                            .format(
                                "%nUnable to detect if it is a mirror or not still fetching MRs anyway...%n");
                        List<MergeRequest> mrs = gitLabApi.getMergeRequestApi()
                            .getMergeRequests(gitlabProject, Constants.MergeRequestState.OPENED);
                        mrs = mrs.stream().filter(mr -> mr.getSourceProjectId() != null)
                            .collect(Collectors.toList());
                        request.setMergeRequests(mrs);
                    } else {
                        listener.getLogger()
                            .format(
                                "%nCollecting MRs for fork except those that target its upstream...%n");
                        List<MergeRequest> mrs = gitLabApi.getMergeRequestApi()
                            .getMergeRequests(gitlabProject, Constants.MergeRequestState.OPENED);
                        mrs = mrs.stream().filter(mr -> mr.getSourceProjectId() != null && mr.getTargetProjectId() != gitlabProject.getForkedFromProject().getId() )
                            .collect(Collectors.toList());
                        request.setMergeRequests(mrs);
                    }
```

**Comment by Tingles** [comment]
+1 I've also run into this.

**Comment by UltimateGeek** [comment]
+1 This issue also impacts my work.

**Comment by coreegor** [comment]
Hello @TBBle,
Do you have any plans to implement this feature ?
