### ISSUE TITLE
Pipeline status always show as pending even when build succeed

### ISSUE THREAD

**Issue by tommy04062019** [jenkinsci/gitlab-branch-source-plugin#209]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu

### Reproduction steps

1. Setup Project with multi branch pipeline using [gitlab-branch-source-plugin](https://github.com/jenkinsci/gitlab-branch-source-plugin
2. Commit code to repo.
3. Pipeline trigged to run
4. Pipeline run success without error.

### Expected Results

- The result of pipeline status should be return in any case.

### Actual Results

Pipeline status on GitLab always stuck at pending status--> Build queued.

**Comment by tommy04062019** [comment]
I figured out that it doesn't work if I used the Remote Jenkinsfile Provider Plugin . For other build modes(Jenkinsfile is located repo), it works as expected. I don't know if there is any way to handle this problem , maybe from this plugin or from RJPP?

**Comment by tommy04062019** [comment]
I checked Github Branch Source works expected with Remote Jenkins Provider, so this plugin should be fixed to work with RJPP

**Comment by syskiller86** [comment]
Same problem

**Comment by tommy04062019** [comment]
The issue was reported at [JENKINS-68635](https://issues.jenkins.io/browse/JENKINS-68635?)
