### ISSUE TITLE
MAJOR CHANGE: access token scope change to global instead of system after version 1.5.9

### ISSUE THREAD

**Issue by moshavnik** [jenkinsci/gitlab-branch-source-plugin#221]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

controller: centos 6.4(not really related), jenkins 2.346.1 (not really related)
agents are irrelevant.

### Reproduction steps

1. install plugin version 1.5.9
2. setup gitlab token access and set the token as "system" scoped.
3. all gitlab source branch plugin features are working properly (multibranch pipeline, organizational folders, etc...)
4. update the plugin to any version higher than 1.5.9
5. try to create a new multibranch pipeline -> this step should fail.
6. change the gitlab branch plugin access token scope to global.
7. retry to create a new multibranch pipeline - this step should succeed.

### Expected Results

creating multibranch pipeline should succeed when the gitlab access token is set to system scope (like in version 1.5.9 of the plugin).

### Actual Results

creating multibranch pipeline using gitlab branch plugin higher than 1.5.9 and gitlab access token which is set to system scope does not work.

### Anything else?

changing the scope of the gitlab token from system to global creates a major security breach in the system since it is now available to any user of jenkins, regardless of their role/access rights/etc.

these credentials, used only in the global configuration page, should stay as system scope at all times.

**Comment by moshavnik** [comment]
there is an open security issue regarding this matter [here](https://issues.jenkins.io/browse/SECURITY-2795).
the issue contains a detailed analysis of the problem, and also seems to point in the direction of a proper solution.
I asked the person who wrote the analysis to add it here as well.

**Comment by jetersen** [comment]
@moshavnik I do not have access to that security issue even though I am the only active maintainer left 😢 Could use some more hands especially for those who actively use gitlab.
