### ISSUE TITLE
Generated URLs for MR, commits, tags, etc. no longer working

### ISSUE THREAD

**Issue by ChristopherZellermann** [jenkinsci/gitlab-branch-source-plugin#320]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  ```text
Jenkins: 2.375.3
OS: Linux - 4.15.0-206-generic
Java: 11.0.18 - Ubuntu (OpenJDK 64-Bit Server VM)
---
.......
gitlab-api:5.0.1-78.v47a_45b_9f78b_7
gitlab-branch-source:646.vb_9560d64b_69f
gitlab-plugin:1.7.7
.........
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux - Ubuntu 18.04

### Reproduction steps

Create a multibranch pipeline job, configure it with your GitLab Project (we use https://gitlab.com/ and not an on premise version of gitlab).

Create a merge request to start the job.

### Expected Results

The links that are generated on the Jenkins UI contain the correct url to view the MR

The 'Merge Request' link on the left panel
![jenkins1](https://github.com/jenkinsci/gitlab-branch-source-plugin/assets/26925275/92cbfd1a-266e-465d-ad60-d168f6d8eda2)

The links after 'Checking merge request'
![jenkins2](https://github.com/jenkinsci/gitlab-branch-source-plugin/assets/26925275/24ed6685-a005-4c76-a34f-4d9d1efd25d8)

### Actual Results

We get a 404 when clicking on the links.
This is because the generated link is https://gitlab.com/xxx/yyy/merge_requests/13142 
but the correct link would be https://gitlab.com/xxx/yyy/-/merge_requests/13142 with the dash seperator '/-/'.

There is the same seperator missing for links to commits, tree, tags, etc.

Also the job is still working. The issue is only with the links that are displayed on the Jenkins web interface.

### Anything else?

It seems like that all recent projects on GitLab have now these '/-/' seperators in the url when accessing MR, commits and so on.
Note that the base URL for the project is still the same https://gitlab.com/xxx/yyy/. Calling just https://gitlab.com/xxx/yyy/-/ will also result in 404.

I found these links on the GitLab project discussing the topic of the dash seperator : 
https://gitlab.com/gitlab-org/gitlab/-/issues/214217
https://gitlab.com/gitlab-org/gitlab/-/issues/273668

**Comment by jmini** [comment]
Great finding. I think this is solved by this change:
https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/322

**Comment by jmini** [comment]
Fixed in version: [660.vd45c0f4c0042](https://github.com/jenkinsci/gitlab-branch-source-plugin/releases/tag/660.vd45c0f4c0042)
